// DATA_VERSION: June 2026
const KA_INGREDIENTS = [
  { name: "'00' Pizza Flour", volume: "1 cup", ounces: "4", grams: "116" },
  { name: "Agave syrup", volume: "1/4 cup", ounces: "3", grams: "84" },
  { name: "All-Purpose Baking Mix", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "All-Purpose Flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Almond butter", volume: "1/4 cup", ounces: "2 1/3", grams: "68" },
  { name: "Almond Flour", volume: "1 cup", ounces: "3 3/8", grams: "96" },
  { name: "Almond meal", volume: "1 cup", ounces: "3", grams: "84" },
  { name: "Almond paste (packed)", volume: "1 cup", ounces: "9 1/8", grams: "259" },
  { name: "Almonds (sliced)", volume: "1/2 cup", ounces: "1 1/2", grams: "43" },
  { name: "Almonds (slivered)", volume: "1/2 cup", ounces: "2", grams: "57" },
  { name: "Almonds, whole (unblanched)", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Amaranth flour", volume: "1 cup", ounces: "3 5/8", grams: "103" },
  { name: "Apple juice concentrate", volume: "1/4 cup", ounces: "2 1/2", grams: "70" },
  { name: "Apples (dried, diced)", volume: "1 cup", ounces: "3", grams: "85" },
  { name: "Apples (peeled, sliced)", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Applesauce", volume: "1 cup", ounces: "9", grams: "255" },
  { name: "Apricots (dried, diced)", volume: "1/2 cup", ounces: "2 1/4", grams: "64" },
  { name: "Artisan Bread Flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Artisan Bread Topping", volume: "1/4 cup", ounces: "1 1/2", grams: "43" },
  { name: "Baker's Cinnamon Filling", volume: "1 cup", ounces: "5 3/8", grams: "152" },
  { name: "Baker's Fruit Blend", volume: "1 cup", ounces: "4 1/2", grams: "128" },
  { name: "Baker's Special Sugar (superfine sugar, castor sugar)", volume: "1 cup", ounces: "6 3/4", grams: "190" },
  { name: "Baking powder", volume: "1 teaspoon", ounces: "1/8", grams: "4" },
  { name: "Baking soda", volume: "1/2 teaspoon", ounces: "1/10", grams: "3" },
  { name: "Baking Sugar Alternative", volume: "1 cup", ounces: "6", grams: "170" },
  { name: "Bananas (mashed)", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Barley (cooked)", volume: "1 cup", ounces: "7 5/8", grams: "215" },
  { name: "Barley (pearled)", volume: "1 cup", ounces: "7 1/2", grams: "213" },
  { name: "Barley flakes", volume: "1/2 cup", ounces: "1 5/8", grams: "46" },
  { name: "Barley flour", volume: "1 cup", ounces: "3", grams: "85" },
  { name: "Barley malt syrup", volume: "2 tablespoons", ounces: "1 1/2", grams: "42" },
  { name: "Basil pesto", volume: "2 tablespoons", ounces: "1", grams: "28" },
  { name: "Bell peppers (fresh)", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Berries (frozen)", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Better Cheddar Cheese Powder", volume: "1/2 cup", ounces: "2", grams: "57" },
  { name: "Blueberries (dried)", volume: "1 cup", ounces: "5 1/2", grams: "156" },
  { name: "Blueberries (fresh or frozen)", volume: "1 cup", ounces: "5 to 6", grams: "140 to 170" },
  { name: "Blueberry juice", volume: "1 cup", ounces: "8 1/2", grams: "241" },
  { name: "Boiled cider", volume: "1/4 cup", ounces: "3", grams: "85" },
  { name: "Bran cereal", volume: "1 cup", ounces: "2 1/8", grams: "60" },
  { name: "Bread Flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Breadcrumbs (dried)", volume: "1/4 cup", ounces: "1", grams: "28" },
  { name: "Breadcrumbs (fresh)", volume: "1/4 cup", ounces: "3/4", grams: "21" },
  { name: "Breadcrumbs (Japanese Panko)", volume: "1 cup", ounces: "1 3/4", grams: "50" },
  { name: "Brown rice (cooked)", volume: "1 cup", ounces: "6", grams: "170" },
  { name: "Brown rice flour", volume: "1 cup", ounces: "4 1/2", grams: "128" },
  { name: "Brown sugar (dark or light, packed)", volume: "1 cup", ounces: "7 1/2", grams: "213" },
  { name: "Buckwheat (whole)", volume: "1 cup", ounces: "6", grams: "170" },
  { name: "Buckwheat Flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Bulgur", volume: "1 cup", ounces: "5 3/8", grams: "152" },
  { name: "Butter", volume: "8 tablespoons (1/2 cup)", ounces: "4", grams: "113" },
  { name: "Buttermilk", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Buttermilk Biscuit Flour Blend", volume: "1 cup", ounces: "3 7/8", grams: "110" },
  { name: "Buttermilk powder", volume: "2 tablespoons", ounces: "2/3", grams: "18" },
  { name: "Cacao nibs", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Cake Enhancer", volume: "2 tablespoons", ounces: "1/2", grams: "14" },
  { name: "Candied Lemon Peel", volume: "1/4 cup", ounces: "1 1/3", grams: "37" },
  { name: "Candied Orange Peel", volume: "1/4 cup", ounces: "7/8", grams: "25" },
  { name: "Caramel (14-16 individual pieces, 1\" squares)", volume: "1/2 cup", ounces: "5", grams: "142" },
  { name: "Caramel bits (chopped Heath or toffee)", volume: "1 cup", ounces: "5 1/2", grams: "156" },
  { name: "Caraway seeds", volume: "2 tablespoons", ounces: "5/8", grams: "18" },
  { name: "Carrots (cooked and puréed)", volume: "1/2 cup", ounces: "4 1/2", grams: "128" },
  { name: "Carrots (diced)", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Carrots (grated)", volume: "1 cup", ounces: "3 1/2", grams: "99" },
  { name: "Cashews (chopped)", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Cashews (whole)", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Celery (diced)", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Cheese (Feta)", volume: "1/2 cup", ounces: "2", grams: "57" },
  { name: "Cheese (grated cheddar, jack, mozzarella, or Swiss)", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Cheese (grated Parmesan)", volume: "1/2 cup", ounces: "1 3/4", grams: "50" },
  { name: "Cheese (Ricotta)", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Cherries (candied)", volume: "1/4 cup", ounces: "1 3/4", grams: "50" },
  { name: "Cherries (dried)", volume: "1/2 cup", ounces: "2 1/2", grams: "71" },
  { name: "Cherries (fresh, pitted, chopped)", volume: "1/2 cup", ounces: "2 7/8", grams: "80" },
  { name: "Cherries (frozen)", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Cherry Concentrate", volume: "2 tablespoons", ounces: "1 1/2", grams: "42" },
  { name: "Chia seeds", volume: "1/4 cup", ounces: "1 1/3", grams: "37" },
  { name: "Chickpea flour", volume: "1 cup", ounces: "3", grams: "85" },
  { name: "Chives (fresh)", volume: "1/2 cup", ounces: "3/4", grams: "21" },
  { name: "Chocolate (chopped)", volume: "1 cup", ounces: "6", grams: "170" },
  { name: "Chocolate Chips", volume: "1 cup", ounces: "6", grams: "170" },
  { name: "Chocolate Chunks", volume: "1 cup", ounces: "6", grams: "170" },
  { name: "Chocolate Mousse Mix", volume: "1/4 cup", ounces: "1", grams: "28" },
  { name: "Cinnamon Sweet Bits", volume: "1/4 cup", ounces: "1 1/4", grams: "35" },
  { name: "Cinnamon-Sugar", volume: "1/4 cup", ounces: "1 3/4", grams: "50" },
  { name: "Climate Blend Flour", volume: "1 cup", ounces: "4", grams: "115" },
  { name: "Cocoa (unsweetened)", volume: "1/2 cup", ounces: "1 1/2", grams: "42" },
  { name: "Coconut (sweetened, shredded)", volume: "1 cup", ounces: "3", grams: "85" },
  { name: "Coconut (toasted)", volume: "1 cup", ounces: "3", grams: "85" },
  { name: "Coconut (unsweetened, desiccated)", volume: "1 cup", ounces: "3", grams: "85" },
  { name: "Coconut (unsweetened, large flakes)", volume: "1 cup", ounces: "2 1/8", grams: "60" },
  { name: "Coconut (unsweetened, shredded)", volume: "1 cup", ounces: "1 7/8", grams: "53" },
  { name: "Coconut cream (unsweetened)", volume: "1 cup", ounces: "10", grams: "284" },
  { name: "Coconut Flour", volume: "1 cup", ounces: "4 1/2", grams: "128" },
  { name: "Coconut milk (evaporated)", volume: "1 cup", ounces: "8 1/2", grams: "242" },
  { name: "Coconut Milk Powder", volume: "1/2 cup", ounces: "2", grams: "57" },
  { name: "Coconut milk, canned, well shaken", volume: "1 cup", ounces: "8 1/2", grams: "241" },
  { name: "Coconut oil", volume: "1/2 cup", ounces: "4", grams: "113" },
  { name: "Coconut sugar", volume: "1/2 cup", ounces: "2 3/4", grams: "77" },
  { name: "Confectioners' sugar (unsifted)", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Cookie butter", volume: "1/4 cup", ounces: "2 1/2", grams: "72" },
  { name: "Cookie crumbs", volume: "1 cup", ounces: "3", grams: "85" },
  { name: "Corn (fresh or frozen)", volume: "1/4 cup", ounces: "1 1/3", grams: "38" },
  { name: "Corn (popped)", volume: "4 cups", ounces: "3/4", grams: "21" },
  { name: "Corn syrup", volume: "1 cup", ounces: "11", grams: "312" },
  { name: "Cornmeal (whole)", volume: "1 cup", ounces: "4 7/8", grams: "138" },
  { name: "Cornmeal (yellow, Quaker)", volume: "1 cup", ounces: "5 1/2", grams: "156" },
  { name: "Cornstarch", volume: "1/4 cup", ounces: "1", grams: "28" },
  { name: "Cottage cheese", volume: "1/2 cup", ounces: "4", grams: "113" },
  { name: "Cracked wheat", volume: "1 cup", ounces: "5 1/4", grams: "149" },
  { name: "Cranberries (dried)", volume: "1/2 cup", ounces: "2", grams: "57" },
  { name: "Cranberries (fresh or frozen)", volume: "1 cup", ounces: "3 1/2", grams: "99" },
  { name: "Cream (heavy cream, light cream, or half & half)", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Cream cheese", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Cream of coconut", volume: "1/2 cup", ounces: "5", grams: "142" },
  { name: "Crème fraiche", volume: "1/2 cup", ounces: "4", grams: "113" },
  { name: "Currants", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Dates (chopped)", volume: "1 cup", ounces: "5 1/4", grams: "149" },
  { name: "Demerara sugar", volume: "1 cup", ounces: "7 3/4", grams: "220" },
  { name: "Dried Blueberry Powder", volume: "1/4 cup", ounces: "1", grams: "28" },
  { name: "Dried milk (Baker's Special Dry Milk)", volume: "1/4 cup", ounces: "1", grams: "28" },
  { name: "Dried nonfat milk (powdered)", volume: "1/4 cup", ounces: "1", grams: "28" },
  { name: "Dried potato flakes (instant mashed potatoes)", volume: "1/2 cup", ounces: "1 1/2", grams: "43" },
  { name: "Dried whole milk (powdered)", volume: "1/2 cup", ounces: "1 3/4", grams: "50" },
  { name: "Durum Flour", volume: "1 cup", ounces: "4 3/8", grams: "124" },
  { name: "Easy Roll Dough Improver", volume: "2 tablespoons", ounces: "5/8", grams: "18" },
  { name: "Egg (fresh)", volume: "1 large", ounces: "1 3/4", grams: "50" },
  { name: "Egg white (fresh)", volume: "1 large", ounces: "1 to 1 1/4", grams: "30 to 35" },
  { name: "Egg whites (dried)", volume: "2 tablespoons", ounces: "3/8", grams: "11" },
  { name: "Egg yolk (fresh)", volume: "1 large", ounces: "1/2", grams: "14" },
  { name: "Espresso Powder", volume: "1 tablespoon", ounces: "1/4", grams: "7" },
  { name: "Everything Bagel Topping", volume: "1/4 cup", ounces: "1 1/4", grams: "35" },
  { name: "Figs (dried, chopped)", volume: "1 cup", ounces: "5 1/4", grams: "149" },
  { name: "First Clear Flour", volume: "1 cup", ounces: "3 3/4", grams: "106" },
  { name: "Flax meal", volume: "1/2 cup", ounces: "1 3/4", grams: "50" },
  { name: "Flaxseed", volume: "1/4 cup", ounces: "1 1/4", grams: "35" },
  { name: "Formaggio Italiano Cheese and Herb Blend", volume: "1/4 cup", ounces: "1", grams: "30" },
  { name: "French-Style Flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Fruitcake Fruit Blend", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Garlic (cloves, in skin for roasting)", volume: "1 large head", ounces: "4", grams: "113" },
  { name: "Garlic (minced)", volume: "2 tablespoons", ounces: "1", grams: "28" },
  { name: "Garlic (peeled and sliced)", volume: "1 cup", ounces: "5 1/4", grams: "149" },
  { name: "Ghee", volume: "1/4 cup", ounces: "1 1/2", grams: "44" },
  { name: "Ginger (fresh, sliced)", volume: "1/4 cup", ounces: "2", grams: "57" },
  { name: "Gluten-Free All-Purpose Baking Mix", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Gluten-Free All-Purpose Flour", volume: "1 cup", ounces: "5 1/2", grams: "156" },
  { name: "Gluten-Free Bread Flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Gluten-Free Measure for Measure Flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Gluten-Free Pizza Flour", volume: "1 cup", ounces: "3 1/2", grams: "100" },
  { name: "Gluten-Free sourdough starter (made with Gluten-Free Bread Flour)", volume: "1 cup", ounces: "6 to 6 1/2", grams: "170 to 185" },
  { name: "Gluten-Free sourdough starter (made with Gluten-Free Measure for Measure Flour)", volume: "1 cup", ounces: "8 to 8 1/2", grams: "227 to 241" },
  { name: "Glutinous rice flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Golden Wheat Flour", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Graham cracker crumbs", volume: "1 cup (6 to 7 crackers)", ounces: "3 1/2", grams: "100" },
  { name: "Granola", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Grape Nuts", volume: "1/2 cup", ounces: "2", grams: "57" },
  { name: "Guava paste", volume: "1/4 cup", ounces: "3 1/2", grams: "100" },
  { name: "Harvest Grains Blend", volume: "1/2 cup", ounces: "2 5/8", grams: "74" },
  { name: "Hazelnut flour", volume: "1 cup", ounces: "3 1/8", grams: "89" },
  { name: "Hazelnut Praline Paste", volume: "1/2 cup", ounces: "5 1/2", grams: "156" },
  { name: "Hazelnut spread", volume: "1/2 cup", ounces: "5 5/8", grams: "160" },
  { name: "Hazelnuts (whole)", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Hi-Maize Natural Fiber", volume: "1/4 cup", ounces: "1 1/8", grams: "32" },
  { name: "High-Gluten Flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Honey", volume: "1 tablespoon", ounces: "3/4", grams: "21" },
  { name: "Instant Clearjel", volume: "1 tablespoon", ounces: "3/8", grams: "11" },
  { name: "Irish-Style Flour", volume: "1 cup", ounces: "3 7/8", grams: "110" },
  { name: "Italian Herb Seasoning", volume: "2 tablespoons", ounces: "1/2", grams: "14" },
  { name: "Italian-Style Flour", volume: "1 cup", ounces: "3 3/4", grams: "106" },
  { name: "Jam or preserves", volume: "1/4 cup", ounces: "3", grams: "85" },
  { name: "Jammy Bits", volume: "1 cup", ounces: "6 1/2", grams: "184" },
  { name: "Keto Wheat Flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Keto Wheat Pizza Crust Mix", volume: "1 cup", ounces: "3 7/8", grams: "110" },
  { name: "Key Lime Juice", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Lard", volume: "1/2 cup", ounces: "4", grams: "113" },
  { name: "Leeks (diced)", volume: "1 cup", ounces: "3 1/4", grams: "92" },
  { name: "Lemon Crumbles", volume: "1 cup", ounces: "6 1/3", grams: "180" },
  { name: "Lemon Curd", volume: "1/2 cup", ounces: "4", grams: "113" },
  { name: "Lemon juice", volume: "1 tablespoon", ounces: "1/2", grams: "14" },
  { name: "Lemon Juice Powder", volume: "2 tablespoons", ounces: "5/8", grams: "18" },
  { name: "Lime Juice Powder", volume: "2 tablespoons", ounces: "5/8", grams: "18" },
  { name: "Macadamia nuts (whole)", volume: "1 cup", ounces: "5 1/4", grams: "149" },
  { name: "Malt syrup", volume: "2 tablespoons", ounces: "1 1/2", grams: "43" },
  { name: "Malted Milk Powder", volume: "1/4 cup", ounces: "1 1/4", grams: "35" },
  { name: "Malted Wheat Flakes", volume: "1/2 cup", ounces: "2 1/4", grams: "64" },
  { name: "Maple Cinnamon French Toast Sugar", volume: "1/4 cup", ounces: "1 2/3", grams: "48" },
  { name: "Maple Cream", volume: "2 tablespoons", ounces: "1 1/2", grams: "42" },
  { name: "Maple sugar", volume: "1/2 cup", ounces: "2 3/4", grams: "78" },
  { name: "Maple syrup", volume: "1/2 cup", ounces: "5 1/2", grams: "156" },
  { name: "Marshmallow Fluff", volume: "1 cup", ounces: "4 1/2", grams: "128" },
  { name: "Marshmallow spread, homemade", volume: "1 cup", ounces: "2 1/2", grams: "72" },
  { name: "Marshmallow spread, store-bought", volume: "1 cup", ounces: "4 1/3", grams: "123" },
  { name: "Marshmallows (mini)", volume: "1 cup", ounces: "1 1/2", grams: "43" },
  { name: "Marzipan", volume: "1 cup", ounces: "10 1/8", grams: "290" },
  { name: "Masa Harina", volume: "1 cup", ounces: "3 1/4", grams: "93" },
  { name: "Mascarpone cheese", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Mashed potatoes", volume: "1 cup", ounces: "7 1/2", grams: "213" },
  { name: "Mashed sweet potatoes", volume: "1 cup", ounces: "8 1/2", grams: "240" },
  { name: "Matcha powder", volume: "2 tablespoons", ounces: "3/8", grams: "12" },
  { name: "Mayonnaise", volume: "1/2 cup", ounces: "4", grams: "113" },
  { name: "Medium Rye Flour", volume: "1 cup", ounces: "3 3/4", grams: "106" },
  { name: "Meringue powder", volume: "1/4 cup", ounces: "1 1/2", grams: "43" },
  { name: "Milk (evaporated)", volume: "1/2 cup", ounces: "4", grams: "113" },
  { name: "Milk (fresh)", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Millet (whole)", volume: "1/2 cup", ounces: "3 5/8", grams: "103" },
  { name: "Mini chocolate chips", volume: "1 cup", ounces: "6 1/4", grams: "177" },
  { name: "Mini Diced Ginger", volume: "1/2 cup", ounces: "2 1/2", grams: "73" },
  { name: "Molasses", volume: "1/4 cup", ounces: "3", grams: "85" },
  { name: "Mushrooms (sliced)", volume: "1 cup", ounces: "2 3/4", grams: "78" },
  { name: "Non-Diastatic Malt Powder", volume: "2 tablespoons", ounces: "5/8", grams: "18" },
  { name: "Nutella", volume: "1/2 cup", ounces: "5 1/4", grams: "149" },
  { name: "Oat bran", volume: "1/2 cup", ounces: "1 7/8", grams: "53" },
  { name: "Oat Flour", volume: "1 cup", ounces: "3 1/4", grams: "92" },
  { name: "Oats (King Arthur Rolled)", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Oats (old-fashioned or quick-cooking)", volume: "1 cup", ounces: "3 1/8", grams: "89" },
  { name: "Oats (prepared)", volume: "1 cup", ounces: "5 1/8", grams: "147" },
  { name: "Olive oil", volume: "1/4 cup", ounces: "1 3/4", grams: "50" },
  { name: "Olives (sliced)", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Onions (fresh, diced)", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Paleo Baking Flour", volume: "1 cup", ounces: "3 5/8", grams: "104" },
  { name: "Palm shortening", volume: "1/4 cup", ounces: "1 1/2", grams: "45" },
  { name: "Passion fruit purée", volume: "1/3 cup", ounces: "2 1/8", grams: "60" },
  { name: "Pasta Flour Blend", volume: "1 cup", ounces: "5 1/8", grams: "145" },
  { name: "Pastry Flour", volume: "1 cup", ounces: "3 3/4", grams: "106" },
  { name: "Pastry Flour Blend", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Peaches (peeled and diced)", volume: "1 cup", ounces: "6", grams: "170" },
  { name: "Peanut butter", volume: "1/2 cup", ounces: "4 3/4", grams: "135" },
  { name: "Peanuts (whole, shelled)", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Pears (peeled and diced)", volume: "1 cup", ounces: "5 3/4", grams: "163" },
  { name: "Pecan Meal", volume: "1 cup", ounces: "2 3/4", grams: "80" },
  { name: "Pecans (diced)", volume: "1/2 cup", ounces: "2", grams: "57" },
  { name: "Pecans (whole)", volume: "1 cup", ounces: "3 3/4", grams: "105" },
  { name: "Pie Filling Enhancer", volume: "1/4 cup", ounces: "1 5/8", grams: "46" },
  { name: "Pine nuts", volume: "1/2 cup", ounces: "2 1/2", grams: "71" },
  { name: "Pineapple (crushed, drained)", volume: "1 cup", ounces: "9", grams: "256" },
  { name: "Pineapple (dried)", volume: "1/2 cup", ounces: "2 1/2", grams: "71" },
  { name: "Pineapple (fresh or canned, diced)", volume: "1 cup", ounces: "6", grams: "170" },
  { name: "Pistachio nuts (shelled)", volume: "1/2 cup", ounces: "2 1/8", grams: "60" },
  { name: "Pistachio Paste", volume: "1/4 cup", ounces: "2 3/4", grams: "78" },
  { name: "Pizza Dough Flavor", volume: "2 tablespoons", ounces: "4/10", grams: "12" },
  { name: "Pizza Flour Blend", volume: "1 cup", ounces: "4 3/8", grams: "124" },
  { name: "Pizza sauce", volume: "1/4 cup", ounces: "2", grams: "57" },
  { name: "Pizza Seasoning", volume: "2 tablespoons", ounces: "1/3", grams: "10" },
  { name: "Polenta (coarse ground cornmeal)", volume: "1 cup", ounces: "5 3/4", grams: "163" },
  { name: "Poppy seeds", volume: "2 tablespoons", ounces: "5/8", grams: "18" },
  { name: "Potato Flour", volume: "1/4 cup", ounces: "1 5/8", grams: "46" },
  { name: "Potato starch", volume: "1 cup", ounces: "5 3/8", grams: "152" },
  { name: "Pumpernickel Flour", volume: "1 cup", ounces: "3 3/4", grams: "106" },
  { name: "Pumpkin purée", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Pumpkin seeds", volume: "1/4 cup", ounces: "1 3/8", grams: "40" },
  { name: "Queso fresco", volume: "1/2 cup", ounces: "2", grams: "57" },
  { name: "Quinoa (cooked)", volume: "1 cup", ounces: "6 1/2", grams: "184" },
  { name: "Quinoa (whole)", volume: "1 cup", ounces: "6 1/4", grams: "177" },
  { name: "Quinoa flour", volume: "1 cup", ounces: "3 7/8", grams: "110" },
  { name: "Raisins (loose)", volume: "1 cup", ounces: "5 1/4", grams: "149" },
  { name: "Raisins (packed)", volume: "1/2 cup", ounces: "3", grams: "85" },
  { name: "Raspberries (fresh)", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Rhubarb (sliced, 1/2\" slices)", volume: "1 cup", ounces: "4 1/4 to 5", grams: "120 to 140" },
  { name: "Rice (long grain, dry)", volume: "1/2 cup", ounces: "3 1/2", grams: "99" },
  { name: "Rice flour (white)", volume: "1 cup", ounces: "5", grams: "142" },
  { name: "Rice Krispies", volume: "1 cup", ounces: "1", grams: "28" },
  { name: "Rye Bread Improver", volume: "2 tablespoons", ounces: "1/2", grams: "14" },
  { name: "Rye Chops", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Rye flakes", volume: "1 cup", ounces: "4 3/8", grams: "124" },
  { name: "Rye Flour Blend", volume: "1 cup", ounces: "3 3/4", grams: "106" },
  { name: "Salt (Kosher, Diamond Crystal)", volume: "1 tablespoon", ounces: "1/4", grams: "8" },
  { name: "Salt (Kosher, Morton's)", volume: "1 tablespoon", ounces: "1/2", grams: "16" },
  { name: "Salt (table)", volume: "1 tablespoon", ounces: "2/3", grams: "18" },
  { name: "Scallions (sliced)", volume: "1 cup", ounces: "2 1/4", grams: "64" },
  { name: "Self-Rising Flour", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Semolina Flour", volume: "1 cup", ounces: "5 3/4", grams: "163" },
  { name: "Sesame seeds", volume: "1/2 cup", ounces: "2 1/2", grams: "71" },
  { name: "Shallots (peeled and sliced)", volume: "1 cup", ounces: "5 1/2", grams: "156" },
  { name: "Six-Grain Blend", volume: "1 cup", ounces: "4 1/2", grams: "128" },
  { name: "Snow White Non-Melting Topping Sugar", volume: "1/2 cup", ounces: "2", grams: "57" },
  { name: "Sorghum flour", volume: "1 cup", ounces: "4 7/8", grams: "138" },
  { name: "Sour cream", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Sourdough starter", volume: "1 cup", ounces: "8 to 8 1/2", grams: "227 to 241" },
  { name: "Soy flour", volume: "1/4 cup", ounces: "1 1/4", grams: "35" },
  { name: "Sparkling Sugar", volume: "1/4 cup", ounces: "2", grams: "57" },
  { name: "Spelt Flour", volume: "1 cup", ounces: "3 1/2", grams: "99" },
  { name: "Sprouted Wheat Flour", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Steel cut oats", volume: "1/2 cup", ounces: "2 1/2", grams: "70" },
  { name: "Sticky Bun Sugar", volume: "1 cup", ounces: "3 1/2", grams: "99" },
  { name: "Strawberries (fresh sliced)", volume: "1 cup", ounces: "5 7/8", grams: "167" },
  { name: "Sugar (granulated white)", volume: "1 cup", ounces: "7", grams: "198" },
  { name: "Sugar substitute (Splenda)", volume: "1 cup", ounces: "7/8", grams: "25" },
  { name: "Sundried tomatoes (dry pack)", volume: "1 cup", ounces: "6", grams: "170" },
  { name: "Sunflower seeds", volume: "1/4 cup", ounces: "1 1/4", grams: "35" },
  { name: "Super 10 Blend", volume: "1 cup", ounces: "3 3/4", grams: "106" },
  { name: "Swedish Pearl Sugar", volume: "1/4 cup", ounces: "1 3/4", grams: "49" },
  { name: "Sweetened condensed coconut milk", volume: "1 cup", ounces: "10 1/8", grams: "288" },
  { name: "Sweetened condensed milk", volume: "1/4 cup", ounces: "2 3/4", grams: "78" },
  { name: "Tahini paste", volume: "1/2 cup", ounces: "4 1/2", grams: "128" },
  { name: "Tapioca (quick cooking)", volume: "2 tablespoons", ounces: "3/4", grams: "21" },
  { name: "Tapioca starch or flour", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Teff flour", volume: "1 cup", ounces: "4 3/4", grams: "135" },
  { name: "The Works Bread Topping", volume: "1/4 cup", ounces: "1 1/4", grams: "35" },
  { name: "Toasted Almond Flour", volume: "1 cup", ounces: "3 3/8", grams: "96" },
  { name: "Toffee chunks", volume: "1 cup", ounces: "5 1/2", grams: "156" },
  { name: "Tomato paste", volume: "2 tablespoons", ounces: "1", grams: "29" },
  { name: "Tropical Fruit Blend", volume: "1 cup", ounces: "4 1/2 to 5", grams: "128 to 142" },
  { name: "Turbinado sugar (raw)", volume: "1 cup", ounces: "6 3/8", grams: "180" },
  { name: "Unbleached Cake Flour", volume: "1 cup", ounces: "4 1/4", grams: "120" },
  { name: "Vanilla Extract", volume: "1 tablespoon", ounces: "1/2", grams: "14" },
  { name: "Vegetable oil", volume: "1 cup", ounces: "7", grams: "198" },
  { name: "Vegetable shortening", volume: "1/4 cup", ounces: "1 5/8", grams: "46" },
  { name: "Vital Wheat Gluten", volume: "2 tablespoons", ounces: "5/8", grams: "18" },
  { name: "Walnuts (chopped)", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Walnuts (whole)", volume: "1/2 cup", ounces: "2 1/4", grams: "64" },
  { name: "Water", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Wheat berries (red)", volume: "1 cup", ounces: "6 1/2", grams: "184" },
  { name: "Wheat bran", volume: "1/2 cup", ounces: "1 1/8", grams: "32" },
  { name: "Wheat germ", volume: "1/4 cup", ounces: "1", grams: "28" },
  { name: "White Chocolate Chips", volume: "1 cup", ounces: "6", grams: "170" },
  { name: "White Rye Flour", volume: "1 cup", ounces: "3 3/4", grams: "106" },
  { name: "Whole Grain Flour Blend", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Whole Wheat Flour (Premium 100%)", volume: "1 cup", ounces: "4", grams: "113" },
  { name: "Whole Wheat Pastry Flour / Graham Flour", volume: "1 cup", ounces: "3 3/8", grams: "96" },
  { name: "Yeast (instant)", volume: "2 teaspoons", ounces: "1/5", grams: "6" },
  { name: "Yeast (instant)", volume: "2 1/4 teaspoons", ounces: "1/4", grams: "7" },
  { name: "Yeast (instant)", volume: "1 tablespoon", ounces: "1/3", grams: "9" },
  { name: "Yogurt", volume: "1 cup", ounces: "8", grams: "227" },
  { name: "Yuletide Cheer Fruit Blend", volume: "1 cup", ounces: "4 1/2", grams: "130" },
  { name: "Zucchini (shredded)", volume: "1 cup", ounces: "4 1/4 to 5 1/4", grams: "121 to 150" }
];
